### ISSUE TITLE
exspec failure

### ISSUE THREAD

**Issue by sbailey** [sbailey/specter#8]
PIXFILE=$DESI_ROOT/spectro/sim/alpha-5/20150211/pix-z0-00000001.fits
PSFFILE=$DESI_ROOT/spectro/redux/sjb/cedar2/calib2d/20150107/psf-z0-00000000.fits

[edison extract] exspec -i $PIXFILE     --psf $PSFFILE     --bundlesize 25     --wavelength 9000,9100,1.5     --specrange 475,500     --output frame-1.5.fits
#--- Extraction Parameters ---
input:      /project/projectdirs/desi/spectro/sim/alpha-5/20150211/pix-z0-00000001.fits
psf:        /project/projectdirs/desi/spectro/redux/sjb/cedar2/calib2d/20150107/psf-z0-00000000.fits
output:     frame-1.5.fits
wavelength: 9000.0 - 9100.0 AA steps 1.5
specrange:  475 - 500
bundlesize: 25
regularize: 0.0
#-----------------------------
Spectra (475, 500) wavelengths (8989.50, 9099.00) -> (9000.00, 9075.00)
Traceback (most recent call last):
  File "/project/projectdirs/desi/software/edison/specter/0.2.4/bin/exspec", line 122, in <module>
    Rd[ispec-specmin, :, iwave+j-nlo] = Rx[j-ndiag:j+ndiag+1, j]
ValueError: could not broadcast input array from shape (0) into shape (21)

**Comment by sbailey** [comment]
--specrange broke now?  This example fails with

Traceback (most recent call last):
  File "/global/homes/s/sjbailey/dev/specter/bin/exspec", line 51, in <module>
    psf_wavemin = np.max(psf.wavelength(range(specmin, specmax+1), y=0))
  File "/global/homes/s/sjbailey/dev/specter/lib/specter/psf/psf.py", line 469, in wavelength
    return self._w.eval(ispec, y)
  File "/global/homes/s/sjbailey/dev/specter/lib/specter/util/traceset.py", line 38, in eval
    y = [legval(xx, self._coeff[i]) for i in ispec]
IndexError: index 500 is out of bounds for axis 0 with size 500

changing 500 -> 499 allows the initial bug report to work now after ac111b2.  Leave open to check/fix specrange usage.

**Comment by sbailey** [comment]
--specrange was broken at upper limit.  Fixed with commit 8c283fd.
